version: "3.8"

services:
  database:
    image: postgres
    container_name: database-ignite
    restart: always
    ports:
      - 5435:5435
    environment:
      - POSTGRES_USER=SYSDBA
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .

    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
